//loaders
export const REQUEST_USERS = 'REQUEST_USERS';
export const USERS_RESPONSE = 'USERS_RESPONSE';
export const ENABLE_SEARCH_LOADER = 'ENABLE_SEARCH_LOADER';
export const DISABLE_SEARCH_LOADER = 'DISABLE_SEARCH_LOADER';
